Fix lib magic installation
StingraySoftware/dave pull request #73
Opened 2018-06-27 23:50 UTC by ricardovb

Fixed bug while installing LibMagic and also fixed bug with missing early log messages on log panel.

2018-06-29 10:04 UTC, pbalm requested changes

2018-06-29 10:04 UTC, pbalm commented on setup/setup.bash
> +       OUTPUT="$(/usr/local/bin/brew install libmagic 2>&1 > /dev/null)"
I think this is wrong. You’re sending stderr to stdout with “2>&1” and then you send stdout to dev null. So what’s OUTPUT going to be? The return code? Poor choice of var name then ;-) I think you should remove the part where you send stdout to dev null: “> /dev/null”. Just remove that section of the command.

2018-06-29 10:04 UTC, pbalm commented on src/main/resources/bash/create_env.bash
> +					echo "|      sudo /opt/local/bin/port install file"
Port install libmagic?

2018-06-29 10:04 UTC, pbalm commented on src/main/resources/bash/create_env.bash
> +					echo "|  - Or relaunch DAVE as root running this command on the terminal:"
Port install libmagic?

2018-06-30 11:26 UTC, ricardovb commented
Applied suggested changes, and also improved error checking while installing LibMagic with MacPorts

2018-06-30 11:41 UTC, merged